AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['(\A|\s)#']
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 120

Style/SymbolArray:
  Exclude:
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
