# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d27b6388bef652eb3e6c1a76e3430c5c0ae93a2f7c7ebfaa879561ea9765b7c754ae012753f98d0f2783207e48773f97cbc04f6d68f78484cc35f53ac4ff4300
  seed_email: <%= ENV["TEST_EMAIL"] %>
  seed_username: <%= ENV["TEST_USERNAME"] %>
  seed_password: <%= ENV["TEST_PASSWORD"] %>
  client_port: <%= ENV["CLIENT_PORT"] %>
  server_port: <%= ENV["SERVER_PORT"] %>

test:
  secret_key_base: 7ddbdeec7503327ca196dbf96651353dfd0b3766c1e8345092cab3277257beb910aa9d6364be2c8442ebc02829b4bdc8d185d1496c5efb0c1be5d1e58f591b43

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
